# Generated by Django 3.0.8 on 2020-07-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='athor',
            new_name='author',
        ),
    ]
