# Generated by Django 3.0.8 on 2020-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200718_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
